
CREATE DATABASE IF NOT EXISTS NodeProject;

USE NodeProject;

DROP TABLE IF EXISTS users;

CREATE TABLE users(
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    PASSWORD VARCHAR(50) NOT NULL,
    status BOOL DEFAULT TRUE,
    createdAt TIMESTAMP,
    updatedAt TIMESTAMP
);

SELECT * FROM users;