CREATE DATABASE IF NOT EXISTS NodeProject;

USE NodeProject;

CREATE TABLE user(
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL,
    status BOOL DEFAULT TRUE
);
